### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by smaragdus** [medo64/Summae#1]
Currently (as of [version](https://www.medo64.com/summae/history/) **1.40**) [Summae](https://www.medo64.com/summae/) saves settings (both the installer and the archive versions) to Windows registry:

`HKEY_CURRENT_USER\Software\Josip Medved\Summae`

I would appreciate if the archive version can be used in portable mode- settings saved not in Windows registry but in configuration file inside program folder (perhaps **Summae.cfg**), just like [Bimil](https://www.medo64.com/bimil/) and [QText](https://www.medo64.com/qtext/) work. I suppose that portable mode would not be hard to be implemented.

**Comment by medo64** [comment]
Yes, that should be feasible. I will look into it over weekend.

**Comment by smaragdus** [comment]
@medo64 

> Yes, that should be feasible. I will look into it over weekend.

Thank you.

**Comment by medo64** [comment]
Hi,

The first version with the new configuration handling is added in commit #a724cb64. I'll work on it some more over weekend but this will be the general approach. Zips and executables are available under [releases](https://github.com/medo64/Summae/releases).

PS: Right-click menu setup still has to go into registry - but one has option of not setting that up.

**Comment by smaragdus** [comment]
@medo64 

Thank you for the notification. I will download the pre-release and check it tonight and tomorrow.

> PS: Right-click menu setup still has to go into registry - but one has option of not setting that up.

For context menu integration Windows registry cannot be avoided. My question- if I enable the context menu integration and then disable it will the registry keys be deleted or they will stay?

**Comment by medo64** [comment]
They should be deleted. I will check it tonight too - before I close the issue.

**Comment by smaragdus** [comment]
II asked because as far as I can remember while I tested version  1.40 several days ago when I disabled shell integration these keys remained in registry.

I have just checked **Summae** version **0.0.6908.41513** and when I disabled shell integration the shell keys were not deleted:

`HKEY_CLASSES_ROOT\*\shell\Summae`

![snipaste-2018-12-01_211109](https://user-images.githubusercontent.com/9025757/49331964-e8484d80-f5ad-11e8-9296-4951a55de894.png)

`HKEY_CURRENT_USER\Software\Classes\*\shell\Summae`

![snipaste-2018-12-01_211149](https://user-images.githubusercontent.com/9025757/49331966-ee3e2e80-f5ad-11e8-9fae-6e628377edec.png)

Also I encountered another problem with the shell integration- **Summae** menu appears in Windows shell but I cannot open the cascading menu (**Summae** sub-menus), this happens under Windows 8 x64. Can you confirm this problem?

**Comment by medo64** [comment]
Problem confirmed and resolved in the [latest release](https://github.com/medo64/Summae/releases).

**Comment by smaragdus** [comment]
@medo64 

I have just checked **Summae** version **0.0.6910.40054** and everything works as expected:

1. settings saved in 'Summae.cfg' for portable version;
2. shell sub-menus (Summae cascading menu) are accessible;
3. after disabling shell integration registry keys are deleted;

Excellent work, thank you.
