### ISSUE TITLE
Always on Top

### ISSUE THREAD

**Issue by smaragdus** [medo64/Summae#2]
I would like to suggest a new button in the tool bar- **Always on top** ('Ctrl+T' would be logical shortcut key) which will facilitate the use of drag&drop. I suppose this will be easy to be implemented.

**Comment by medo64** [comment]
Next weekend it is. :)

**Comment by smaragdus** [comment]
@medo64 

Thanks.

**Comment by medo64** [comment]
Implemented in commit #eeee45a. Available in [releases](https://github.com/medo64/Summae/releases).

**Comment by smaragdus** [comment]
@medo64 

Thank you.
