### ISSUE TITLE
'Copy' Button

### ISSUE THREAD

**Issue by smaragdus** [medo64/Summae#3]
I would like to suggest new button in 'hashes' window- 'Copy' (perhaps before 'Save' button), screen:

![summae 0 0 6910 40054 - 2018-12-07 - 004](https://user-images.githubusercontent.com/9025757/49667621-4a98c680-fa64-11e8-95b5-52f7d628456e.png)

If such 'Copy' button is available the user would be able to copy the hash value via a single click.

**Comment by medo64** [comment]
Implemented in commit #303cd68. Available in [releases](https://github.com/medo64/Summae/releases).

**Comment by smaragdus** [comment]
@medo64 

Excellent:

![summae 0 0 6916 41265 - 2018-12-09 - 001](https://user-images.githubusercontent.com/9025757/49699400-4f32bb80-fbd9-11e8-8c0f-680392c44040.png)

Now copying hash via single click is possible. Thanks!

**Comment by smaragdus** [comment]
**Off-topic**

I discovered by chance a nice undocumented feature- if there is hash in clipboard after the hashes are calculated if the  clipboard hash matches one of the calculated hashes it is shown in green, screen:

![summae 0 0 6916 41265 - 2018-12-09 - 002](https://user-images.githubusercontent.com/9025757/49699632-2cee6d00-fbdc-11e8-98bf-291a36e2aa44.png)

This is very nice!
