### ISSUE TITLE
Spaces in Hashes

### ISSUE THREAD

**Issue by smaragdus** [medo64/Summae#4]
I noticed that [Summae](https://www.medo64.com/summae/) puts spaces in the calculated hashes and separates these hashes into parts, examples (**summae140.exe**):

- **MD5:**

  -  _**Summae hash:**_ 563c464a a4dc8d8f 0860fa35 fe71271d
  - _**Actual hash:**_ 563c464aa4dc8d8f0860fa35fe71271d
 
- **RIPEMD160:** 

  - _**Summae hash:**_ 18146f17 e294d2f7 3bc69a34 e075a558 ed1dc5d1
  - _**Actual hash:**_ 18146f17e294d2f73bc69a34e075a558ed1dc5d1

- **SHA1:**

  - **_Summae hash:_** 5526e4e0 b06b77d9 e7a124b1 97d2d976 25eb1752
  - _**Actual hash:**_ 5526e4e0b06b77d9e7a124b197d2d97625eb1752
 
- **SHA256:**
 
  - **_Summae hash:_** d1a03921a052f782 9ba2df75629540f2 7860c59376e646e7 6d7d0f83ffb753a2
  - **_Actual hash:_** d1a03921a052f7829ba2df75629540f27860c59376e646e76d7d0f83ffb753a2
 
- **SHA384:**
 
  - _**Summae hash:**_ 87f39547a3f998e8 c5abcad112f6e8c3 19674f1a2c437e79 c7f95531b596059e bf0ed59e56af6c1d ef6e147a4a89204a
  - _**Actual hash:**_ 87f39547a3f998e8c5abcad112f6e8c319674f1a2c437e79c7f95531b596059ebf0ed59e56af6c1def6e147a4a89204a
 
- **SHA512:**

  - _**Summae hash:**_ 52a11fd25db7904f fe3aa4e8af280e74 a96c88f5ae209941 72ded6437fca5b04 cf3fcf58a5997bf4 efeef6bd6c0bc5ed f690f15057f7752a 2ceb33b6f951aa87
  - _**Actual hash:**_ 52a11fd25db7904ffe3aa4e8af280e74a96c88f5ae20994172ded6437fca5b04cf3fcf58a5997bf4efeef6bd6c0bc5edf690f15057f7752a2ceb33b6f951aa87

**Screen:**

![summae 0 0 6910 40054 - 2018-12-07 - 005](https://user-images.githubusercontent.com/9025757/49668875-2939d980-fa68-11e8-8e02-8f2f9d9b7362.png)

I do not know whether this is done on purpose or this is a bug but for me this is undesired behaviour- I need hashes without any spaces inside.

If this is a bug- please fix it, if it is not- please add an option to calculate hashes without any spaces inside.

**Comment by medo64** [comment]
Not a bug. :)
I have added an option to change it.
![image](https://user-images.githubusercontent.com/8540228/49693629-3d93da00-fb2d-11e8-8089-3b45657155b0.png)
Available in the latest [release](https://github.com/medo64/Summae/releases).

**Comment by smaragdus** [comment]
@medo64 

Thank you. I am glad that 'Add spaces to hash' is not checked by default- these spaces might be confusing for some users.
