### ISSUE TITLE
UPPER CASE

### ISSUE THREAD

**Issue by smaragdus** [medo64/Summae#7]
You may add new check box in 'Options' - 'UPPER CASE', when it is checked the hashes will be shown in upper case, example:

`D2440D09EEB6A53AE049EE6934377F52BE880491BEDC18434AE01B23416C13D4` (UPPER CASE)

in stead of

`d2440d09eeb6a53ae049ee6934377f52be880491bedc18434ae01b23416c13d4` (lower case)

Some users prefer UPPER CASE for hashes in stead of lower case.

**Comment by medo64** [comment]
Implemented in commit #7ef1e698.

**Comment by smaragdus** [comment]
@medo64 

Thank you! This might be an insignificant feature but it adds some convenience.
